# Generated by Django 3.0.2 on 2020-03-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_auto_20200219_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='minutestitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
